version: '3'

services:
  api:
    build:
      context: .
      args:
        CHANNEL_TASKS_PACKAGE: $CHANNEL_TASKS_PACKAGE
    ports:
      - 8001:8001
    depends_on:
      - db
    environment:
      - TASK_ADMIN_USER
      - TASK_ADMIN_EMAIL
      - CHANNEL_TASKS_LOG_LEVEL
      - CHANNEL_TASKS_DOCKER_HOME
      - CHANNEL_TASKS_BIN_DIR
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - LANGUAGE=C:en
    command: sh -c "$CHANNEL_TASKS_BIN_DIR/setup-channel-tasks.sh && exec /usr/local/bin/docker-entrypoint.sh unitd --no-daemon"
  db:
    image: postgres:latest
    environment:
      - PGPORT=5433
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:latest
