# Generated by Django 4.2.1 on 2023-05-08 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('task_id', models.PositiveBigIntegerField()),
                ('scheduled_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('completed_at', models.DateTimeField(null=True)),
                ('document', models.JSONField(null=True)),
            ],
        ),
    ]
